### ISSUE TITLE
Function to convert GPS data to OD Matrix

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/stplanr#11]
This would be useful. Any ideas @richardellison ? Will take a look if so!

**Comment by richardellison** [comment]
I think this would be better off as several separate issues/functions as 
converting from raw GPS data to an OD matrix requires several steps:

1. Clean the GPS data, possibly starting off with a Kalman filter or 
something similar.
2. Defining and identifying "trips" (including mode changes)
3. Identifying the true origins and destinations for trips
4. Aggregating trips to OD matrices

Each of these has been implemented to varying degrees of success using 
different algorithms but I think really need to be tackled separately as 
they build on each other, and can be useful in isolation as well. I 
suggest we start off by implementing the first of these steps as this 
can be the hardest step and most complicated for people to understand 
conceptually.

**Comment by Robinlovelace** [comment]
Totally agree - many thanks for this. Will close for now and refer back to this when adding GPS functionality.
